# Generated by Django 4.1.2 on 2022-11-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description_of_product', models.CharField(max_length=100)),
                ('number_of_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreAccessories',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('prod_type', models.CharField(default='Rackets', max_length=40)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='StoreClothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('size', models.CharField(max_length=2)),
                ('prod_type', models.CharField(default='T-Shirt', max_length=40)),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products_added', models.IntegerField()),
                ('name_of_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
