# Generated by Django 4.1.2 on 2022-10-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description_of_product', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=2)),
                ('number_of_products', models.IntegerField()),
            ],
        ),
    ]
