# Generated by Django 4.1.2 on 2022-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prod_type',
            field=models.CharField(default='T-Shirt', max_length=30),
        ),
    ]
