# Generated by Django 4.1.2 on 2022-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_prod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='genre',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
