# Generated by Django 4.1.2 on 2022-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img_not_found.png', upload_to=''),
        ),
    ]
