# Generated by Django 4.1.2 on 2022-11-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='genre',
            new_name='gender',
        ),
    ]
