# Generated by Django 4.1.2 on 2022-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_genre_store_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description_of_product', models.CharField(max_length=100)),
                ('number_of_products', models.IntegerField()),
                ('prod_type', models.CharField(default='Rackets', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreClothes',
        ),
    ]
