# Generated by Django 4.1.2 on 2022-11-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_of_product',
            field=models.CharField(max_length=500),
        ),
    ]
