# Generated by Django 4.1.2 on 2022-11-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_of_product',
            field=models.CharField(max_length=50),
        ),
    ]
