# Generated by Django 4.1.2 on 2022-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_name_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeclothes',
            name='color',
            field=models.CharField(default='Black', max_length=152),
        ),
    ]
