# Generated by Django 4.1.2 on 2022-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storeclothes_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeclothes',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Black', max_length=152),
        ),
    ]
