# Generated by Django 4.1.2 on 2022-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_storeclothes_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('purple', 'Purple'), ('orange', 'Orange')], default='black', max_length=152),
        ),
    ]
