# Generated by Django 4.1.2 on 2022-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('deeppink', 'Pink')], default='black', max_length=152),
        ),
    ]
