# Generated by Django 4.1.2 on 2022-11-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('number_of_products_added', models.IntegerField()),
                ('price', models.IntegerField()),
                ('clothes_size', models.CharField(max_length=2)),
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accessories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeaccessories')),
                ('clothes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeclothes')),
            ],
        ),
    ]
