# Generated by Django 4.1.2 on 2022-11-19 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_name_of_product'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('number_of_products_added', models.IntegerField()),
                ('price', models.IntegerField()),
                ('clothes_size', models.CharField(max_length=2)),
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accessories_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storeaccessories')),
                ('clothes_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storeclothes')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
