# Generated by Django 4.1.2 on 2022-11-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_color'),
        ('cart', '0002_shoppingcart_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCartRenamed',
        ),
    ]
