# Generated by Django 4.1.2 on 2022-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_shoppingcart_shoppingcartrenamed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='used_coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
