# Generated by Django 4.1.2 on 2025-05-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number_of_titles',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Unknown', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
